### ISSUE TITLE
スラッシュつきのキーが正しくパースできない

### ISSUE THREAD

**Issue by kyohsuke** [kyohsuke/yaml-key.vim#1]
```yaml
ja:
  errors:
    some/errors:
      foo: bar
```

こういうやつ
